sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake  --quiet
branches:
  only:
  - master
env:
  global:
    secure: BPhqBgr/jXmgBZ6sqmYWVXMkumi8j1pjPzxpOgwFaA7mW3vY4g3rvmlp+dfmzhn+bx4x4V2zkaqyECZB1yqlmjX6xmjo/LpKpJ9aIZF2PvPX4Xt+JNafR9k7VEM8Z4oK9X66vK18wlPhEnzXTWueK06QbeaUjQ6Wx7bDIsNCxoZBpfUZf20EcabiCEeSqWa7qARncaa5iYGB0triAHbO51RKZMKrItJiIzS7wMpwNLJZlms1UF4uVAdR/pWbCttatF88xiH8TOIrz8QBi+UtBAROO7qSuDV5I//LniGrs0cj5TrkO20HQx8y/sRVFPf+omTwsk/C7uL4ANnOehTtAt3sbo/AtRbFAv/jaQx2pysQRD8Afcs5CDHYyJu/SbhqvdJf2k+0XUfoSgy39cit+FALL21cW4HOPqJkfeSypwKVb6Nr+JQlhV26whymIxFxB1vFcIHLF0p0Al8JlVBKux/G66xm50yxMW2ypza+8QNqruce0/7nVHbCCrc/IgjHOZjPq20y/s6v3VX9gA8Oaen+lUFBRrepyq7Jy/MmM5+0vLgS7riiHvfG1XnEWUMSyyM5twM3OrFkieepbEzgnGLyKs6mwqGXP7dyujHmQdd0Q1HLvThzjg0bTZFUN5yx3szPxXneuoFVtWfGO4Rx16xJxtYVKckgEPS/5cZyDOM=
notifications:
  slack:
    secure: EQXeytGfleMmBKQ8GQTuytvAIJL2IGEsYf3Ymsv/Qx71BCpJBlc0SXB3wgARH68BrQR9nK0L+HoEiMRfOmLBboQ6iq3Uj8GtVVvsOfHXszGaEax8pRJLdVUXiiyyzvnI82hamSe4P6iTtpMcvA81ZcRGkktyePX3HmNL0g745TZDXElqAyz0EEZ3/P8aYeTcBhWOH5XmgfkGs834mG+lsFwDRVSoaBugG5cptOqfWjV90LDrn5/jqIPjJviIOAzOp+O/2xe6VYDxGQyecqBDZL1czSxOFOVJAF0zqzqnwrLajRsso25prJXYHJ9n1TM7pGpWq9Orna9OzWhHJt3VS9TLa0Bb/2CvH01ifURXwigoWThph4r5O1OBMh2LzpROL70ocZvmzAdmJOq0zvo+97/YXvrghEmpzePQzwzv8fnef0p5a3vuDFj6DrwkrrHLbWDZJ4ewVCqzJPMAD4RGUZzYPLRgQLryBiNYMuRmIn7Z0WMDoaYqIiuqB0naUO7N/cKkVy881eSjFopEk8pSH8Z8gSv1t28r0EHcvqwIYOCFlezOfJfU2ofUlv+ChkLXtzU25kekt7IkbRQFBL/ugfT/pWyipT2Ss4CPfQpMtUub8ouydvztmTD39nn0Ht0TdELPatm84yTbQlcVSdxd+7UefzvXFaJOvKdulJPeibY=
