sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake  --quiet
branches:
  only:
  - master
env:
  global:
    secure: BPhqBgr/jXmgBZ6sqmYWVXMkumi8j1pjPzxpOgwFaA7mW3vY4g3rvmlp+dfmzhn+bx4x4V2zkaqyECZB1yqlmjX6xmjo/LpKpJ9aIZF2PvPX4Xt+JNafR9k7VEM8Z4oK9X66vK18wlPhEnzXTWueK06QbeaUjQ6Wx7bDIsNCxoZBpfUZf20EcabiCEeSqWa7qARncaa5iYGB0triAHbO51RKZMKrItJiIzS7wMpwNLJZlms1UF4uVAdR/pWbCttatF88xiH8TOIrz8QBi+UtBAROO7qSuDV5I//LniGrs0cj5TrkO20HQx8y/sRVFPf+omTwsk/C7uL4ANnOehTtAt3sbo/AtRbFAv/jaQx2pysQRD8Afcs5CDHYyJu/SbhqvdJf2k+0XUfoSgy39cit+FALL21cW4HOPqJkfeSypwKVb6Nr+JQlhV26whymIxFxB1vFcIHLF0p0Al8JlVBKux/G66xm50yxMW2ypza+8QNqruce0/7nVHbCCrc/IgjHOZjPq20y/s6v3VX9gA8Oaen+lUFBRrepyq7Jy/MmM5+0vLgS7riiHvfG1XnEWUMSyyM5twM3OrFkieepbEzgnGLyKs6mwqGXP7dyujHmQdd0Q1HLvThzjg0bTZFUN5yx3szPxXneuoFVtWfGO4Rx16xJxtYVKckgEPS/5cZyDOM=
notifications:
  slack:
    secure: TTitRxJZX43/Pp8tDn5k+PlA2nhfdnyCar+t37PMFpOWb2tMlTmEl6fxuDM5CbotQeHUGj3/ZS790rqD7vKx6gVm6XlmvsJJDP0A7ngMN92hszLaX3pvpwKtijsChgLxqrlaM0VEbBWpzOI4ft+UQhYy6XzIpIBqguhi7pfUfvohGHi0676deU5Rjpiq840MAAXw5Zvyh4OxA4C8f5wTPcXD9Y/Q9Jakg4HZ6NR0E9BcoFYekOFYjbmEPDXLFoVQ5btFnawvvLCO6yoZM54P5yc8Xl9Yd6G3ouj/p+8aoqgPLQehIUtofI+u3UEKEXVh8YTxZVnZEwM3658Fy5nhGthBaWBYZ0jTY5ZjugBXRVEd37uyLg0qDG8pb9obFz93TsbYHr/rvSjsXIchimgt2CyEnmc6SPDllJAonkyp5LOafSrxnKnuGZypQTmoxMExR6i8dxKp/jWCsvwjRn+dbdoBguuTNEP5MLGM31Li/kWl7Y43Wytt0gUfOhU6PCTj10r3iuyBXUYFXNEaw35tNQXW2EVVlncZCYrCWRR0wN5fIy722Mrh7aWVAy3TAhuV9c9FSMQyaiND3mJofAbFRuZohI0XKRR+zuuik2DVssLoZ7DHU7igxbC6QwFwSVDwsRgyMNw4sY5gJm1mRKH7oHq66JVTXTgGHxw8JsAgaVU=
