sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake  --quiet
branches:
  only:
  - master
notifications:
  slack:
    secure: i1KobEaDSGhzEtr1XiLUjEJK7/aOAfWRFnq8yuV4IKhyBUAexmc7wrgmqTJAIRV7MYgEVRym5CXTcLtLWjPnoP+qZqqu7IVo0e4I3AW/AfKcjCsQHJ4FT574vUXOJ56B1bTYTsSv/AcKBib03Gvjg7duzmC+ViuHN39HzL8C+tCSzl16heAe/ol35KbGgnL/R4JBLPVcaNp0H7eolVksRFYAbF54yjAwxt94f8+05dXCrq58gS0vR2nmdKl0/yRstev0vlldqTE3qSgAleH6ad5qr/3BXqJcY48Ko+KDEAkk17lA/ngacM1FiSdxYFKZhPEPZqIpyquaA6datQpYjsbjRlOpBhXovLFo9PbZxSjfoZUL1UosQ46xK+VPIB3mlUBI7Xgkv1N4HfRa9TYf5GIfOab8M4DJAfm/L+esvllfemiwIOkLN4xoiJcNlgvExD2qpQsagl3hb+F8knpXBYtRgsN18tzwQEGZu93ZeB0uaXGvpqg6xoVcuRsy9ZFyKmzqbxZzMMSjcNXk1PYYiqx5gRSUhmgtfBwk+uCPpHbhk1lUp1cGcjAc7ZAP0AvUSeXari3ruK10UpDnFJ4rr28YplW7WyOtqtoMJPz2tYSc7zzMZcctiLRVEi4j2m9jgEAEYs/71hf9yWbgWlF0mdSeKie4cMCf07DN+ynggSg=
env:
  global:
    secure: QrPBDfHYdwefOy3tfQN6gP/QBl5Z55IPnwDkMt+5kq/Xh5c9dS0RrJG1j5A5JoLCx4d7LiUGMXPxwcDqslM1ip1jDUiPlbNSbzBvliiIR7fg6zYHF2KuOSx5MGTNbdytBVdE+H6uMYX5KNehpe9NKMecyHTevt1zPxmWnbA4/RJGNG+65+Z9sA3oqXWLhW7NwddRcIMnTVMi64AfzuoiXkbbVV8ckS/lFLwn//r2GfQjcIcKhnAG3roffFUz96NaL24l3w8tX5nBbuNLVzrsKpU9wbL9sd74nJw+pzpNbnAkXkCSWq6TLvlJgWbu/HQDWDu44XB/8xrylB7hO82uJGpCX7Fp0+kp85x5GfMuVmoLsrAxHynVQCSMsh9rNYHBzzR91BQx18DD0dDI6eQ78BZL4a8LQo0h85/g8t6ZT7jiISvmN4VkMuTsBTV8CcoKvdbzHt/6ovqTW8KIJgrDJWR2hOfPsmQ1reWX8kg4g3gTSdPfbpnYhDEUx2B17e9n0GsTz5WxZcBp4NGzecGIdzUjTW81LM47enXGFvDpEshscFsb1zyyUs9IL8ysVyf7H5NptHItIHNVDIciO0LbPAcbNvluw/f82/iK5ynyhDSx/RiCqipSA086zsTkIy87BbQuYhvPOUFDgTsrNt3rUQd2Je/yjUrY9SODZ1FIf3U=
