sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake  --quiet
branches:
  only:
  - master
env:
  global:
    secure: BPhqBgr/jXmgBZ6sqmYWVXMkumi8j1pjPzxpOgwFaA7mW3vY4g3rvmlp+dfmzhn+bx4x4V2zkaqyECZB1yqlmjX6xmjo/LpKpJ9aIZF2PvPX4Xt+JNafR9k7VEM8Z4oK9X66vK18wlPhEnzXTWueK06QbeaUjQ6Wx7bDIsNCxoZBpfUZf20EcabiCEeSqWa7qARncaa5iYGB0triAHbO51RKZMKrItJiIzS7wMpwNLJZlms1UF4uVAdR/pWbCttatF88xiH8TOIrz8QBi+UtBAROO7qSuDV5I//LniGrs0cj5TrkO20HQx8y/sRVFPf+omTwsk/C7uL4ANnOehTtAt3sbo/AtRbFAv/jaQx2pysQRD8Afcs5CDHYyJu/SbhqvdJf2k+0XUfoSgy39cit+FALL21cW4HOPqJkfeSypwKVb6Nr+JQlhV26whymIxFxB1vFcIHLF0p0Al8JlVBKux/G66xm50yxMW2ypza+8QNqruce0/7nVHbCCrc/IgjHOZjPq20y/s6v3VX9gA8Oaen+lUFBRrepyq7Jy/MmM5+0vLgS7riiHvfG1XnEWUMSyyM5twM3OrFkieepbEzgnGLyKs6mwqGXP7dyujHmQdd0Q1HLvThzjg0bTZFUN5yx3szPxXneuoFVtWfGO4Rx16xJxtYVKckgEPS/5cZyDOM=
notifications:
  slack:
    secure: djj3jKfQUevl7eQfOR7L/eD9VpAw5tWZ6XdtY9qPRgT9B54voxJq8W76d2jSxrvA7h9bQ17ltq5dSLVV6aoAXiyZsFUYe6eO5rfhav+K2sVBFGObx0Dr2AdBmCh2JksBVXP6s7i8RrOufqqpLbxw9YY75Ogv0B5c5mZW5TmeJuJWNRSlI7RCIh4fXE2EM7iazP5/l71msmQOntNrXb4T99pkgiuIfwe9yjGeGm+eyrb+5McLnCTaZipgXZ0YTSA58JWKIEIn1Zjk+K1DbE0GuZ3LfnCITKVGoOLYVk9VSD0RJ6/wT4TBkKpcSf4+oqMipLRkNTBMTQuPQ/f+fH728rwNRIkS+z3Yl1SmU9kiJzgxVTQEBp1Z50k+J2PeA/B427/MjaW1dlFVGw+3dp1e9AYLva/CTe6yCVO1J66i1iytpG5Td3mvL1IiM6R9yXym+EnOkOvpwBnMZ/9WbplOt60weMDf+kPCmudRCz7wLkM/lCFNS0zigjbWuSeF50/V02z06w2co04bWSqQd0nDgeOb5FxprRWRc8hKw/UP0Z7njWZv2huWBxc+0IBpT27d14H874Ijt1N+uluc7ZbB9CJ1484Z1PtXPknnV6/5uXk3aNSbzBf8+ARZDrpT8Sounqq4vkGTHcwaIC0O+Q03JKrC/cHOLEhLK5glAjGj32U=
