sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake  --quiet
env:
  global:
    secure: p8wkbi8WV4xuOJmErR6Sdy4DZGhZSI4M8wHaEIDHScwmSFXfGs+vgnnnrSoRa08++LYwuBIhA0BDCU12Y+AhmHfqZJkjxvkZMJH38ylmncyWShO0w0KiCg20VQ9q2h80bSxW3jbVsTzDq1a8qRpXhYTMw0geYSpHhxrlpgMaTZs5vAgSX4jTLQar4e2dj/wQbTSVtTMqO06VZYVQVT6nvmOVSSFqpVUmMdQpMVV2RkeDBKnQmJ21j+YXbmEXwpUNziRE+wZOCOJNwuVBnLPbHjyPIlgFjtkYha4wehmne5s8Vhz8+TGFbcZkGN/Pf6eHtnVFeGJcEiXl9UC7v7/IKuANpv7W4CvqJwtNiOEZHxKRkSIMIUVR5rHe5nOmatI3Qa7pub+OBsRAgTHszyQi80J8zospWsidxiRDYuv0ZPy/TJx+cXgPBA3ozqJOpbD/auZ8y5nQMECCmBZjLyHCIYoJrgOwAcrIdNTnvkVB81eOhhE9hRUyhnNamDjsb2W1Sa7w8Djlxf7bu1IZpeJ0xEMZ/vBUgMrC4IYwX1KhmTT/4cImkdTS0R84O6D9y/awkr5VipXAG4rJEnwL8ZwvD+OuKBve88cKQWbbSo3mCuwtnfNJoU7QElsFAn+4joRr5sc4fZBh0xx88Q964pe6On8/ocvSGg4j2Mw6EGwP6XE=
branches:
  only:
  - master
notifications:
  slack:
    secure: anNF+DsBd4O6zSzFIj9IDLvodynOL79cgbJXqr01p9AGKhT9WU/b9f9EfvzoX2aJ8zaTkaYUcOb4WTzrpqKW9igH1ohrIffnDBIPXKTm6NV1MVdSNXKjrg3Ba2sm229kswid5/MZoy1QxsAXflZ69hF8Ac24X/tkg9ocgFhexQ/2JK2mTy1SBUQE6CweqfGQgpCgmfZEQJAThiZ6CMuXhiHUU9ujgKQsn38iKCiNfrkAZ1/kMqiXUsPZMKuFv+3U/5UXlvONDnhcZjL07PQMO0rexTEER73JCIyyjpBnaBxjRvmMy1OEknurscxYr7nuz5fTplMLTzopHeIaWRUmrW3LDiTNAn9A6Un9Kj9DuF9RVSMm0L10Fbv0A7OAJ36ReWZbEotPsOsaPsmJ6QtaP7bVNwl2ME/7u01NQiLx8t2iYVdZT2p8lyZHKmZmdt13ZV4v0cl+B7GnalqWDavzeBrDakgCQ/9j3bm1+F5Vc6Yl6RmPg+qGxj0N3mkn6l0hhOOmj+w6jvyqunE62lBPx11L4o5VKyP7WqsXFIJA6cB6h4iGtUXHS6SxKqu1+e+3NaOcONyQPdXBC+YT9/GsYgvG+GPVnNnPHFETzxBKRiSvEKO7iLxyfltWbrwozj8r8EuMfqxWsbnBxduHKVJ21nbSpP5HSC+LZah5wHsZqqA=