sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake  --quiet
branches:
  only:
  - master
env:
  global:
    secure: BPhqBgr/jXmgBZ6sqmYWVXMkumi8j1pjPzxpOgwFaA7mW3vY4g3rvmlp+dfmzhn+bx4x4V2zkaqyECZB1yqlmjX6xmjo/LpKpJ9aIZF2PvPX4Xt+JNafR9k7VEM8Z4oK9X66vK18wlPhEnzXTWueK06QbeaUjQ6Wx7bDIsNCxoZBpfUZf20EcabiCEeSqWa7qARncaa5iYGB0triAHbO51RKZMKrItJiIzS7wMpwNLJZlms1UF4uVAdR/pWbCttatF88xiH8TOIrz8QBi+UtBAROO7qSuDV5I//LniGrs0cj5TrkO20HQx8y/sRVFPf+omTwsk/C7uL4ANnOehTtAt3sbo/AtRbFAv/jaQx2pysQRD8Afcs5CDHYyJu/SbhqvdJf2k+0XUfoSgy39cit+FALL21cW4HOPqJkfeSypwKVb6Nr+JQlhV26whymIxFxB1vFcIHLF0p0Al8JlVBKux/G66xm50yxMW2ypza+8QNqruce0/7nVHbCCrc/IgjHOZjPq20y/s6v3VX9gA8Oaen+lUFBRrepyq7Jy/MmM5+0vLgS7riiHvfG1XnEWUMSyyM5twM3OrFkieepbEzgnGLyKs6mwqGXP7dyujHmQdd0Q1HLvThzjg0bTZFUN5yx3szPxXneuoFVtWfGO4Rx16xJxtYVKckgEPS/5cZyDOM=
notifications:
  slack:
    secure: GI+3m4PuVxfMj+Ip6+40aSc31GJVfX+BugYlRChaZoXXa9rU2NgK0/PGYMIJtQGfRpqAYHNR6g7t25obz+a+XmHmP2jN0ErOk1rv6RUhPgUQOzSG/mT2gQT/ThxUil3G4LR3S2NVQ4G8c2fhdgL4m7LCzTp1dvu740A9bX5hZ8BuNvLPAoNKJVFXf5udWGhpvS8dclmU2agOE9YTeHzhVzlYxdn1MtVd152DccI8Qm3kdA2r7ujBCLOfSue1NHeMvN8XC1209Ib26taVz6RI7B4y5/Rj/zf/wAY3k5B4WMqVPD4SifPNyM2o1XvATTqOJpOqogidNyEjnWrEIzHEmfL+n/AhGtWQ2y4WwHBZNFkGaW76c3pTJot01E6H6Y4BM86DXXDfulNMOTlYZbHldLI9F3Wk12RsV9CNE6H4wG9by3D7PZ8LfiRAlKZwXqqja1m4WMh63Szu5TMQQ+KxvwFVKpFKNeM6sGU22dtzpjIGI47SYItZjM6n7RPapOMvN6OcvBQZaniXgobATtjzkNazhHZp1cc4wpIYGwv+vW8SRwhyYgARoB/Bs9IvaGcI6tsWEroisuPknkfEatndAR8YvczS98MbFmLCDW1nmptXSLlUh0h5wUKQs3DVLwLsiUFIflS1JPNWOzZojL/QZlabKu+CY3AYvc2g8n+Qkvo=
