sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake  --quiet
env:
  global:
    secure: ATCQHohy73SQGZ5Mad9rLkTU3eJumcUP+XXnW/N4ymPKUEsHRAIxfG88ZJEKK0MCA47jhcHrfWolmrmVSzWtN74V9cWC3NOgyZmJtn8S+y8m2m5cW1bL8DPSXY/uR95NbeYR8Yn5GUmgOBdEztPd9iXxoECp74aMkGxBgITmjfKP9VIoS6uqPcolMCQo1P0UjXMRf9Hpiv5w070nn3HmeeGVb3+TN6T71JwLDIPArSwgZKIK0N4DmowwGQiMeL2g4/r+ha9f/xEw6q3Qzj0MNDf9vIO65gZbRKxfsZyr59q5THqUWPHrbXuNUYA3DX8c0J1AoKhG0RinIfdnNjlGJIRzbMBd+APgA89h/Gf66++HsXEeuSkc9HI+dXRxbjPoWZPZZy3tDy20meUAXnwq1Zo2+Mdux0gVERQzkKS406FUOfwbjF/mdfnnNL5PrsrqeFyyg/she8wTxUxvYrlSJweh7vUrHwpm2Xswbc7wfuK/p44iI+Y/j+4Gw4qxhNEPZ6GJuJoeuz51TUSRLnbX/p3s0xaeRIkHkqTvXyAef4sPzAzpL8WIVo6Ynd3CECHZ3Era0VF0KkndzU5IQSTHuYv3R7/qlHWame+pbe91zi6YcLHCVir+4sYSfTQR54LlsNMa4/oPvoj1RPooEBluRNZlPswcpJ9vqhOpucKEN2A=
branches:
  only:
  - master
notifications:
  slack:
    secure: VU66WCtvDRQOm2GAoq1W7PP9x50C18fkObH9zAnmpRog7JcEkDODoRQKIlltqfoBf7rNmJsTjTyTdya5gSj+yDgJtWVOI/QTCiEH9OCy0uagNfHD3/tQwRUVUxn37gQzJFffk7of83oLd7QnJ9vVBw1bmmMFcP+DwceBI73do4O3KgWNg7FBX1/Hn2I1l2L6Aq+A0WKfFyEUVmc9MZHhdvQEarwm5YfilqzrkFUpXfAHoMKNz2bsh2F67PUStTs7n0FgSranr6Ax4fKPnhavWqYAQPrttCIjuEiUTZfKTt6GvRG6HrNoYWMYkexmKVsAD+5kr6c45tksNvE+JNKXMo/HJgGVoR8kzTOvW8QJ1E2bLaR8KTJlqR3E2/z6jhnjdoIgjM9jgr57+C/mNDRdcpdqgaiQxOHLaebuUXYO+mLt8QA/PNn1ZwSWeEZwc987CJEFO5huZYP9Q3Gveva9tdMT6ISMhJ7RWXcvbf+UWchWaQkcqHJMN7KQrruHDsW9ZI5wdf//ZBaYsmJzbGjwTIMrt6pYWNRL4ugDa6sGhSrJfkkv2CPR4WbXkTuqh9S9asmZvV1l/udorBovo7f88fUJxagxOchR87lTCJ4EfsiJP25OCQc4LlUxDhpNlGjMaVfzL2bm+eW/JumIM5B2bnsuPT8D4E93WnRRZUDKWHU=
